### ISSUE TITLE
Download always failing?

### ISSUE THREAD

**Issue by awangn6600** [lap00zza/9anime-Companion#106] opened 2017-11-25 06:52 UTC
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Is there any change in 9anime side? because when i tried to download any anime from any server, it always gives me Failed message
![image](https://user-images.githubusercontent.com/4899660/33228189-a8b316ea-d1e7-11e7-901a-857d018bea5c.png)
i dont know how to get the error message, tried installing in developer mode and checked console log, nothing appears there

**Comment by lap00zza** [comment] 2017-11-25 07:26
Hi this is most likely happening because 9anime added a server query param for the url used to get videos
![image](https://user-images.githubusercontent.com/8621583/33228382-fdf04072-d1df-11e7-84a5-8111d6d04100.png)

I will try to find a fix for this asap.

**Comment by grabberboy** [comment] 2017-11-25 12:59
@lap00zza 
the problem is more deeper on that

they have encode the token for the grabber url 
encoded using client side javascript
from /all.js

 $.ajax(e.grabber, {
                    data: o,
                    success: function(t) {
                        i[R](uU, e.subtitle),
                        t[Xy] ? t[Xy] === di ? r.Ei(xM + sp + di + sp + kE + sp + vP + sp + kH + sp + ST + sp + Qa + sp + jM + sp + fF + sp + n_) : (r.$i(i, t[Xy], t.token),
                        r.Fi(i, t[Xy])) : r.Xi(i, t[R])
                    },
                    error: function() {
                        i[R](dt) < 1 ? (i[R](dt, i[R](dt) + 1),
                        r.Oi(i, e)) : r.Ei(xM + sp + iz + sp + GU + sp + vP + sp + fF + sp + n_ + Ey + gr)
                    }
                })
            },

**Comment by lap00zza** [comment] 2017-11-25 13:02
@grabberboy yup. I was just looking at it via the chrome debugger sometime back. Thing is this decryption happens sometime between onsuccess/oncomplete and before generating the `_`. But the thing is if I manually step in and trace line by line the decryption function never seems to get called (weird), My best guess is that they put a time duration check during which it can be decrypted.

**Comment by grabberboy** [comment] 2017-11-25 13:12
@lap00zza the time duration is the worst scenario
lets look more on it

**Comment by lap00zza** [comment] 2017-11-26 07:55
My findings till now. I got really tired after being at this for 4 hours. Might take a crack at it again tomorrow. Some of the variables are renamed.
```js
// Tracehelper
window.src = 12
window.fakeSrc = "";
Object.defineProperty(window, "src", {
    configurable: false,
    get() {
        return fakeSrc;
    },
    set(x) {
        console.trace();
        console.log(JSON.parse(JSON.stringify(x)));
        this.fakeSrc = x;
    }
});


/* --- */
// so
// -> ajax call to get link
// -> `success` calls `NI` with the JSON response and the callback `cb`
// -> `NI` calls callback `cb` after 200 ms
// -> `cb` calls `OI` with the epsiode element and `x` (contents of window.src)
//     `x` contains the decoded token and option parameter
// Final observation, js has ~200 ms to decrypt token/option param. IF it gets
// delayed Oi gets called with encrypted token/option.
// ---
// t is the episode element
function success(n) {
    Ni(n, function(x) /*name: cb*/ {
        if(x.error) 
            i.Ei("An error occured please refresh the page (ERR 1)") 
        else
            if (x.type === "direct") 
                Oi(t, x)
            else
                if (x.type === "iframe") 
                    i.Ri(x.target)
    })
}

function Ni(i, n) {
    var e = this;
    window.src = i,
    window.srcsrc = !0, /* !0 = true */
    window.setTimeout(function() {
        i = window.src,
        delete window.src,
        delete window.srcsrc,
        n.call(e, i)
    }, 200)
}

// i is the element
// e is the json object
function Oi(i, e) {
    var r = this
      , o = e.params;
    return i.data("apiErrorCount", i.data("apiErrorCount") || 0),
    $[oI](o, {
        _i: t.XTOKEN,
        mobile: n.mobile() ? 1 : 0
    }),
    $.ajax(e.grabber, {
        data: o,
        success: function(t) {
            i.data("subtitle", e.subtitle),
            if(t.error)
                if (t.error === "token") 
                    r.Ei("API: token invalid please refresh this page and try again") 
                else
                    (r.$i(i, t[Xy], t.token), r.Fi(i, t[Xy])) 
            else
                r.Xi(i, t[R])
        },
        error: function() {/*...*/}
    });
}

// second function responsible for decryption
window.setTimeout(function() {
    if(window.src)
        if(window.srcsrc === true)
            window.srcsrc = false; 
            window.src = decrypt(window.src)
}, 50);

function decrypt(t) {
    var n;
    if (Object.prototype.toString.call(t) === "[object Array]")
        for (n = 0; n < t.length; n++)
            t[n] = decrypt(t[n]);

    else if (Object.prototype.toString.call(t) === "[object Object]")
        for (n in t)
            if(Object.prototype.hasOwnProperty.call(t, n))
                t[n] = decrypt(t[n]);

    else
        typeof t === "string" && (t = t[0] === "." ? function(t, i) {
            var n, e = [];
            if (i || (i = 13),
            !(i %= 26))
                return t;
            for (n = 0,
            l = t.length; n < l; n++)
                c = t.charCodeAt(n),
                c >= 97 && c <= 122 ? e[n] = (c - 71 + i) % 26 + 97 : c >= 65 && c <= 90 ? e[n] = (c - 39 + i) % 26 + 65 : e[n] = c;
            return String.fromCharCode.apply(vA, e)
        }(t.substr(1), -18) : t);
    return t
}
/* --- */

// notes
// -> _ is calculated from the encrypted token and options
```

**Comment by hoppler** [comment] 2017-11-26 08:07
the encryption is rot-8. you have to decrypt all variable values starting with a dot.
1. strip the beginning dot
2. do rot-8
3. done

fore example: in params.token the value starts with a . and options starts with a . (dot) too. if its not a direct link but an iframe, youll see the target starts with a . and has to be decrypted too. thats it, nothing more

**Comment by lap00zza** [comment] 2017-11-26 08:12
@hoppler WOAH thanks so much. I was having trouble identifying. Just tested, it is indeed rot-8.

**Comment by Vysair** [comment] 2017-11-26 10:02
Not just failing, it doesn't even showed up like "Downloading 001" (select all or just one episode) then all "Done".

**Comment by grabberboy** [comment] 2017-11-26 10:03
good findings but still the ts value is encrypted in unknown method

hope @hoppler can see this too

**Comment by lap00zza** [comment] 2017-11-26 10:05
@Vysair the fix will take some time. There were 2 main hindrances:
1. Finding the encryption scheme for token/options (which is solved)
2. Finding the encryption scheme for `ts`

Once the 2nd one is done I will release a fix for the downloads. (Best guess: within max 2 days)

**Comment by hoppler** [comment] 2017-11-26 11:35
Here you go

```python
def main():
    expected = "1511690400"
    ts = "YNPxYNX5YGHwYA=="

    firstCharMap = []
    secondCharMap = []
    for n in range(65, 91):
        firstCharMap.append(chr(n))
        if n % 2 != 0:
            secondCharMap.append(chr(n))
    for n in range(65, 91):
        if n % 2 == 0:
            secondCharMap.append(chr(n))

    result = ""
    for i in range(len(ts)):
        charReplaced = False
        for y in range(len(secondCharMap)):
            if ts[i] == secondCharMap[y]:
                result += firstCharMap[y]
                charReplaced = True
                break
        if not charReplaced:
            result += ts[i]
    import base64
    real_ts = base64.b64decode(result)
    print real_ts
    print "Success" if real_ts == expected else "failure"


if __name__ == '__main__':
    main()
```

**Comment by lap00zza** [comment] 2017-11-26 11:53
Thanks so much @hoppler . For anyone reading this thread, I will release a fix for 9anime Companion tomorrow.

**Comment by lap00zza** [comment] 2017-11-26 13:11
Can someone please test these artifacts: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.24/artifacts and tell me if downloads are working for F2, G2 and G3.

**Comment by TheMiziko** [comment] 2017-11-26 14:07
Can't wait for the fix ! unfortunately can't help with testing because I'm not at home, but hopefully the issue will be resolved till tomorrow !

**Comment by Dibakarroy1997** [comment] 2017-11-26 15:05
Getting this after installing. And download from F2, G2 and G3 still not working.

![screenshot from 2017-11-26 20-31-15](https://user-images.githubusercontent.com/17507690/33241269-1270236e-d2e9-11e7-945a-89f86aa7aab4.png)

![screenshot from 2017-11-26 20-30-59](https://user-images.githubusercontent.com/17507690/33241267-123c94cc-d2e9-11e7-93f9-33c58b0982e2.png)

![screenshot from 2017-11-26 20-31-49](https://user-images.githubusercontent.com/17507690/33241270-12a2c2b0-d2e9-11e7-94c7-1f1df388a22c.png)

**Comment by grabberboy** [comment] 2017-11-26 15:13
they update again

token is not in rot8 anymore

**Comment by SolvingTheWorld** [comment] 2017-11-26 16:14
Maybe they are spying on us? 
I wish i could help but i have been spending too much time watching anime and too little working on my JS skills (i fell bad for it).

Anyways, thank to everyone working on solving this issue and i hope that i can help in future ones.

**Comment by PradipH31** [comment] 2017-11-26 16:34
https://twitter.com/9animeto/status/933685120539561984

They have said it

**Comment by Dibakarroy1997** [comment] 2017-11-26 16:43
Looking at their discord it doesn't seem like they are going to war anyone.

![screenshot from 2017-11-26 22-08-54](https://user-images.githubusercontent.com/17507690/33242164-7a6151de-d2f6-11e7-823a-9eb845d21033.png)

We can only hope that this is only one-time change, and things get stabilize soon.

**Comment by SolvingTheWorld** [comment] 2017-11-26 16:46
Well, that discord message dates september and the tweet is from november so it is a little outdated.

**Comment by lap00zza** [comment] 2017-11-26 16:47
Probably because of a misunderstanding. One of my friend who knows the owner told me the owner thinks:
> when they enabled the adblock detection I made 9anime Companion not work on purpose

But that is not at all true. It was still working if you disabled **Remove Ads** and **Remove Social Share**. But I have no clue why they added detection for social share. Ads I can understand.

**Comment by SolvingTheWorld** [comment] 2017-11-26 16:53
Well, i only started to use 9anime a few days ago, it said "we stopped the pop up's please turn off the adblocker" and so  did but now they are using pop ups again, there is no option to donate or pay to turn off this ads. I believe that a better service will make more donators and more people willing to help. A good way to make the service better is to coexist with this extension that makes the website much better.

**Comment by awangn6600** [comment] 2017-11-26 23:05
Well i dont know if this will help us, but i think you should remove the
ability to hide the ads, maybe by doing that, we are showing to 9anime guys
that we dont have intention to hurt their income

leave adblocking to the users, they can use adblock extensions

**Comment by Dibakarroy1997** [comment] 2017-11-27 02:18
I think @awangn6600 is right. You should probably remove the adblock feature. Also, it would be better if you could talk to the admin of 9anime and figure something out. I assure you people would love to have 9anime companion as an official extension for 9anime.

**Comment by lap00zza** [comment] 2017-11-27 08:53
A fix is on the way but if possible can you guys please share your thought about remove adblocker here: https://www.reddit.com/r/9anime/comments/7ftuvp/poll_9anime_companion_remove_ads/

**Comment by lap00zza** [comment] 2017-11-27 09:14
tentative fix for downloads: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.25/artifacts

**Comment by Dibakarroy1997** [comment] 2017-11-27 09:34
> Remove Remove Ads from the official build (Chrome Web Store, Addons.Mozilla.Org), but still be available in a separate branch in the GitHub repository so that people can compile themselves.

The tentative fix is working.

**Comment by SolvingTheWorld** [comment] 2017-11-27 10:00
Great work, thank you.

**Closed** 2017-11-27 10:05 UTC

**Comment by awangn6600** [comment] 2017-11-27 10:12
@lap00zza rapidvideo removed? i always use rapid video because the download link doesnt expire quickly like google server one

is there any problem with rapidvideo?

**Comment by lap00zza** [comment] 2017-11-27 10:13
@awangn6600 its target link is encrypted as well. I will patch it as soon as I find out how to decrypt.

**Comment by awangn6600** [comment] 2017-11-27 10:20
could you take give me a lead which part of the code to take a look? maybe i can do something about it

**Comment by lap00zza** [comment] 2017-11-27 10:44
@awangn6600 sure. Basically you need to look in a file called `all.js`. But its encrypted (packed js). So you will need to wait till its decrypted and then check the called lines from the f12 Network tab.

**Comment by lap00zza** [comment] 2017-11-27 10:49
@awangn6600 lets continue the rapidvideo discussion here: #109
