### ISSUE TITLE
IDM Download if possible.

### ISSUE THREAD

**Issue by pctechkid** [lap00zza/9anime-Companion#12] opened 2017-04-19 06:08 UTC
A very great extension indeed. One of the few apps out there that is so useful. It would be perfect if you could somehow add the option to download it with IDM.

**Comment by lap00zza** [comment] 2017-04-19 06:10
Thanks. Supporting external download manager is on the list. It will be there in the next release. By the way, this issue is a duplicate of #8 . Is it okay if I close this one?

**Comment by pctechkid** [comment] 2017-04-19 06:24
Oh my bad. Didn't saw that one. Feel free to close this one. I'll wait for the next release. Thanks a lot!

**Closed** 2017-04-19 06:25 UTC
Labels: duplicate
